-- Munna Pen Center — migration 0001_init
-- PART 1: tables, enums, indexes and foreign keys generated by Prisma from prisma/schema.prisma.
-- PART 2 (below): hand-written constraints, triggers and row-level security.
-- REVIEW ONLY until approved by the owner: do not run against Supabase before that.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "AdminRole" AS ENUM ('OWNER', 'STAFF');

-- CreateEnum
CREATE TYPE "ActorType" AS ENUM ('ADMIN', 'AI_AGENT', 'CUSTOMER', 'SYSTEM');

-- CreateEnum
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT', 'ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "CustomerType" AS ENUM ('SCHOOL', 'OFFICE', 'ENGINEER', 'BUSINESS', 'INSTITUTION', 'RETAILER', 'OTHER');

-- CreateEnum
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST');

-- CreateEnum
CREATE TYPE "LeadSource" AS ENUM ('WEBSITE', 'WHATSAPP', 'PHONE', 'REFERRAL', 'AI_AGENT', 'OTHER');

-- CreateEnum
CREATE TYPE "EnquirySource" AS ENUM ('BULK_ORDER_FORM', 'QUOTE_FORM', 'CONTACT_FORM', 'WHATSAPP', 'PHONE', 'AI_AGENT');

-- CreateEnum
CREATE TYPE "EnquiryStatus" AS ENUM ('NEW', 'IN_REVIEW', 'QUOTED', 'WON', 'LOST', 'SPAM');

-- CreateEnum
CREATE TYPE "QuotationStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('PENDING_CONFIRMATION', 'CONFIRMED', 'PROCESSING', 'DISPATCHED', 'DELIVERED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('UPI', 'BANK_TRANSFER', 'CHEQUE', 'CASH', 'CARD', 'OTHER');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'FAILED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "FollowUpType" AS ENUM ('CALL', 'WHATSAPP', 'EMAIL', 'VISIT', 'PAYMENT_REMINDER', 'REPEAT_ORDER');

-- CreateEnum
CREATE TYPE "FollowUpStatus" AS ENUM ('OPEN', 'DONE', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ApprovalAction" AS ENUM ('PROPOSE_PRICE', 'APPLY_DISCOUNT', 'SEND_QUOTATION', 'CONFIRM_ORDER', 'ISSUE_INVOICE', 'REQUEST_PAYMENT', 'SCHEDULE_DELIVERY', 'CANCEL_ORDER', 'SEND_CUSTOMER_MESSAGE');

-- CreateEnum
CREATE TYPE "ApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED');

-- CreateTable
CREATE TABLE "AdminUser" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" "AdminRole" NOT NULL DEFAULT 'STAFF',
    "passwordHash" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastLoginAt" TIMESTAMP(3),
    "failedLoginCount" INTEGER NOT NULL DEFAULT 0,
    "lockedUntil" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AdminSession" (
    "id" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "adminUserId" TEXT NOT NULL,

    CONSTRAINT "AdminSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Category" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "summary" TEXT,
    "description" TEXT,
    "seoTitle" TEXT,
    "seoDescription" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "parentId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Brand" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isListedPublicly" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Brand_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "sku" TEXT,
    "name" TEXT NOT NULL,
    "shortDescription" TEXT,
    "description" TEXT,
    "unit" TEXT,
    "packSize" TEXT,
    "purchasePrice" DECIMAL(12,2),
    "wholesalePrice" DECIMAL(12,2),
    "retailPrice" DECIMAL(12,2),
    "hsnCode" TEXT,
    "gstRatePercent" DECIMAL(5,2),
    "stockQuantity" INTEGER,
    "minOrderQuantity" INTEGER,
    "imageUrl" TEXT,
    "imagePath" TEXT,
    "imageAlt" TEXT,
    "tags" TEXT[],
    "status" "ProductStatus" NOT NULL DEFAULT 'DRAFT',
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "categoryId" TEXT NOT NULL,
    "brandId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "organizationName" TEXT,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "city" TEXT,
    "state" TEXT,
    "source" "LeadSource" NOT NULL DEFAULT 'WEBSITE',
    "status" "LeadStatus" NOT NULL DEFAULT 'NEW',
    "notes" TEXT,
    "assignedToId" TEXT,
    "customerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Customer" (
    "id" TEXT NOT NULL,
    "type" "CustomerType" NOT NULL DEFAULT 'OTHER',
    "organizationName" TEXT NOT NULL,
    "contactName" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "gstin" TEXT,
    "billingLine1" TEXT,
    "billingCity" TEXT,
    "billingState" TEXT,
    "billingPincode" TEXT,
    "shippingLine1" TEXT,
    "shippingCity" TEXT,
    "shippingState" TEXT,
    "shippingPincode" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Customer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Enquiry" (
    "id" TEXT NOT NULL,
    "reference" TEXT NOT NULL,
    "source" "EnquirySource" NOT NULL,
    "status" "EnquiryStatus" NOT NULL DEFAULT 'NEW',
    "productsRequired" TEXT NOT NULL,
    "approximateQuantity" TEXT,
    "additionalRequirements" TEXT,
    "city" TEXT,
    "state" TEXT,
    "leadId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Enquiry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EnquiryItem" (
    "id" TEXT NOT NULL,
    "productId" TEXT,
    "productName" TEXT NOT NULL,
    "quantityNote" TEXT,
    "enquiryId" TEXT NOT NULL,

    CONSTRAINT "EnquiryItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Quotation" (
    "id" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "status" "QuotationStatus" NOT NULL DEFAULT 'DRAFT',
    "createdBy" "ActorType" NOT NULL,
    "validUntil" TIMESTAMP(3),
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "subtotal" DECIMAL(12,2),
    "taxTotal" DECIMAL(12,2),
    "total" DECIMAL(12,2),
    "terms" TEXT,
    "notes" TEXT,
    "sentAt" TIMESTAMP(3),
    "customerId" TEXT NOT NULL,
    "enquiryId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Quotation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuotationItem" (
    "id" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit" TEXT NOT NULL DEFAULT 'pcs',
    "unitPrice" DECIMAL(12,2),
    "hsnCode" TEXT,
    "gstRatePercent" DECIMAL(5,2),
    "lineTotal" DECIMAL(12,2),
    "priceSetBy" "ActorType",
    "priceApprovalId" TEXT,
    "quotationId" TEXT NOT NULL,
    "productId" TEXT,

    CONSTRAINT "QuotationItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Order" (
    "id" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "status" "OrderStatus" NOT NULL DEFAULT 'PENDING_CONFIRMATION',
    "createdBy" "ActorType" NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "subtotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "taxTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "total" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "shippingLine1" TEXT,
    "shippingCity" TEXT,
    "shippingState" TEXT,
    "shippingPincode" TEXT,
    "transporter" TEXT,
    "trackingReference" TEXT,
    "confirmedAt" TIMESTAMP(3),
    "dispatchedAt" TIMESTAMP(3),
    "deliveredAt" TIMESTAMP(3),
    "notes" TEXT,
    "customerId" TEXT NOT NULL,
    "quotationId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OrderItem" (
    "id" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit" TEXT NOT NULL DEFAULT 'pcs',
    "unitPrice" DECIMAL(12,2) NOT NULL,
    "hsnCode" TEXT,
    "gstRatePercent" DECIMAL(5,2) NOT NULL,
    "lineTotal" DECIMAL(12,2) NOT NULL,
    "orderId" TEXT NOT NULL,
    "productId" TEXT,

    CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Invoice" (
    "id" TEXT NOT NULL,
    "number" TEXT,
    "financialYear" TEXT,
    "sequence" INTEGER,
    "status" "InvoiceStatus" NOT NULL DEFAULT 'DRAFT',
    "createdBy" "ActorType" NOT NULL,
    "issueDate" TIMESTAMP(3),
    "dueDate" TIMESTAMP(3),
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "subtotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "cgstTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "sgstTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "igstTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "total" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "buyerName" TEXT,
    "buyerAddress" TEXT,
    "buyerGstin" TEXT,
    "placeOfSupply" TEXT,
    "supplierName" TEXT,
    "supplierAddress" TEXT,
    "supplierGstin" TEXT,
    "irn" TEXT,
    "orderId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InvoiceItem" (
    "id" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit" TEXT NOT NULL DEFAULT 'pcs',
    "unitPrice" DECIMAL(12,2) NOT NULL,
    "hsnCode" TEXT,
    "gstRatePercent" DECIMAL(5,2) NOT NULL,
    "lineTotal" DECIMAL(12,2) NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "productId" TEXT,

    CONSTRAINT "InvoiceItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payment" (
    "id" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "method" "PaymentMethod" NOT NULL,
    "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    "reference" TEXT,
    "gatewayPaymentId" TEXT,
    "paidAt" TIMESTAMP(3),
    "notes" TEXT,
    "invoiceId" TEXT NOT NULL,
    "recordedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FollowUp" (
    "id" TEXT NOT NULL,
    "type" "FollowUpType" NOT NULL,
    "status" "FollowUpStatus" NOT NULL DEFAULT 'OPEN',
    "dueAt" TIMESTAMP(3) NOT NULL,
    "notes" TEXT,
    "createdBy" "ActorType" NOT NULL,
    "completedAt" TIMESTAMP(3),
    "leadId" TEXT,
    "customerId" TEXT,
    "quotationId" TEXT,
    "orderId" TEXT,
    "assignedToId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FollowUp_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ApprovalRequest" (
    "id" TEXT NOT NULL,
    "action" "ApprovalAction" NOT NULL,
    "status" "ApprovalStatus" NOT NULL DEFAULT 'PENDING',
    "requestedBy" "ActorType" NOT NULL,
    "summary" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "payloadHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "decidedAt" TIMESTAMP(3),
    "decisionNote" TEXT,
    "executedAt" TIMESTAMP(3),
    "decidedById" TEXT,
    "decidedByRole" "AdminRole",
    "quotationId" TEXT,
    "orderId" TEXT,
    "invoiceId" TEXT,
    "leadId" TEXT,
    "customerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ApprovalRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NumberSequence" (
    "id" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "financialYear" TEXT NOT NULL,
    "lastValue" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NumberSequence_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AdminUser_email_key" ON "AdminUser"("email");

-- CreateIndex
CREATE UNIQUE INDEX "AdminSession_tokenHash_key" ON "AdminSession"("tokenHash");

-- CreateIndex
CREATE INDEX "AdminSession_adminUserId_idx" ON "AdminSession"("adminUserId");

-- CreateIndex
CREATE INDEX "AdminSession_expiresAt_idx" ON "AdminSession"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug");

-- CreateIndex
CREATE INDEX "Category_parentId_idx" ON "Category"("parentId");

-- CreateIndex
CREATE UNIQUE INDEX "Brand_slug_key" ON "Brand"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Brand_name_key" ON "Brand"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");

-- CreateIndex
CREATE INDEX "Product_categoryId_idx" ON "Product"("categoryId");

-- CreateIndex
CREATE INDEX "Product_brandId_idx" ON "Product"("brandId");

-- CreateIndex
CREATE INDEX "Product_status_idx" ON "Product"("status");

-- CreateIndex
CREATE INDEX "Lead_phone_idx" ON "Lead"("phone");

-- CreateIndex
CREATE INDEX "Lead_status_idx" ON "Lead"("status");

-- CreateIndex
CREATE INDEX "Lead_assignedToId_idx" ON "Lead"("assignedToId");

-- CreateIndex
CREATE INDEX "Lead_customerId_idx" ON "Lead"("customerId");

-- CreateIndex
CREATE INDEX "Customer_phone_idx" ON "Customer"("phone");

-- CreateIndex
CREATE UNIQUE INDEX "Enquiry_reference_key" ON "Enquiry"("reference");

-- CreateIndex
CREATE INDEX "Enquiry_leadId_idx" ON "Enquiry"("leadId");

-- CreateIndex
CREATE INDEX "Enquiry_status_idx" ON "Enquiry"("status");

-- CreateIndex
CREATE INDEX "Enquiry_createdAt_idx" ON "Enquiry"("createdAt");

-- CreateIndex
CREATE INDEX "EnquiryItem_enquiryId_idx" ON "EnquiryItem"("enquiryId");

-- CreateIndex
CREATE INDEX "EnquiryItem_productId_idx" ON "EnquiryItem"("productId");

-- CreateIndex
CREATE UNIQUE INDEX "Quotation_number_key" ON "Quotation"("number");

-- CreateIndex
CREATE INDEX "Quotation_customerId_idx" ON "Quotation"("customerId");

-- CreateIndex
CREATE INDEX "Quotation_enquiryId_idx" ON "Quotation"("enquiryId");

-- CreateIndex
CREATE INDEX "Quotation_status_idx" ON "Quotation"("status");

-- CreateIndex
CREATE INDEX "QuotationItem_quotationId_idx" ON "QuotationItem"("quotationId");

-- CreateIndex
CREATE INDEX "QuotationItem_productId_idx" ON "QuotationItem"("productId");

-- CreateIndex
CREATE INDEX "QuotationItem_priceApprovalId_idx" ON "QuotationItem"("priceApprovalId");

-- CreateIndex
CREATE UNIQUE INDEX "Order_number_key" ON "Order"("number");

-- CreateIndex
CREATE UNIQUE INDEX "Order_quotationId_key" ON "Order"("quotationId");

-- CreateIndex
CREATE INDEX "Order_customerId_idx" ON "Order"("customerId");

-- CreateIndex
CREATE INDEX "Order_status_idx" ON "Order"("status");

-- CreateIndex
CREATE INDEX "OrderItem_orderId_idx" ON "OrderItem"("orderId");

-- CreateIndex
CREATE INDEX "OrderItem_productId_idx" ON "OrderItem"("productId");

-- CreateIndex
CREATE UNIQUE INDEX "Invoice_number_key" ON "Invoice"("number");

-- CreateIndex
CREATE INDEX "Invoice_orderId_idx" ON "Invoice"("orderId");

-- CreateIndex
CREATE INDEX "Invoice_customerId_idx" ON "Invoice"("customerId");

-- CreateIndex
CREATE INDEX "Invoice_status_idx" ON "Invoice"("status");

-- CreateIndex
CREATE UNIQUE INDEX "Invoice_financialYear_sequence_key" ON "Invoice"("financialYear", "sequence");

-- CreateIndex
CREATE INDEX "InvoiceItem_invoiceId_idx" ON "InvoiceItem"("invoiceId");

-- CreateIndex
CREATE INDEX "InvoiceItem_productId_idx" ON "InvoiceItem"("productId");

-- CreateIndex
CREATE INDEX "Payment_invoiceId_idx" ON "Payment"("invoiceId");

-- CreateIndex
CREATE INDEX "Payment_status_idx" ON "Payment"("status");

-- CreateIndex
CREATE INDEX "FollowUp_status_dueAt_idx" ON "FollowUp"("status", "dueAt");

-- CreateIndex
CREATE INDEX "FollowUp_leadId_idx" ON "FollowUp"("leadId");

-- CreateIndex
CREATE INDEX "FollowUp_customerId_idx" ON "FollowUp"("customerId");

-- CreateIndex
CREATE INDEX "ApprovalRequest_status_createdAt_idx" ON "ApprovalRequest"("status", "createdAt");

-- CreateIndex
CREATE INDEX "ApprovalRequest_quotationId_idx" ON "ApprovalRequest"("quotationId");

-- CreateIndex
CREATE INDEX "ApprovalRequest_orderId_idx" ON "ApprovalRequest"("orderId");

-- CreateIndex
CREATE INDEX "ApprovalRequest_invoiceId_idx" ON "ApprovalRequest"("invoiceId");

-- CreateIndex
CREATE INDEX "ApprovalRequest_leadId_idx" ON "ApprovalRequest"("leadId");

-- CreateIndex
CREATE INDEX "ApprovalRequest_customerId_idx" ON "ApprovalRequest"("customerId");

-- CreateIndex
CREATE UNIQUE INDEX "NumberSequence_scope_financialYear_key" ON "NumberSequence"("scope", "financialYear");

-- AddForeignKey
ALTER TABLE "AdminSession" ADD CONSTRAINT "AdminSession_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Category" ADD CONSTRAINT "Category_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Enquiry" ADD CONSTRAINT "Enquiry_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EnquiryItem" ADD CONSTRAINT "EnquiryItem_enquiryId_fkey" FOREIGN KEY ("enquiryId") REFERENCES "Enquiry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EnquiryItem" ADD CONSTRAINT "EnquiryItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Quotation" ADD CONSTRAINT "Quotation_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Quotation" ADD CONSTRAINT "Quotation_enquiryId_fkey" FOREIGN KEY ("enquiryId") REFERENCES "Enquiry"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuotationItem" ADD CONSTRAINT "QuotationItem_priceApprovalId_fkey" FOREIGN KEY ("priceApprovalId") REFERENCES "ApprovalRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuotationItem" ADD CONSTRAINT "QuotationItem_quotationId_fkey" FOREIGN KEY ("quotationId") REFERENCES "Quotation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuotationItem" ADD CONSTRAINT "QuotationItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_quotationId_fkey" FOREIGN KEY ("quotationId") REFERENCES "Quotation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InvoiceItem" ADD CONSTRAINT "InvoiceItem_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InvoiceItem" ADD CONSTRAINT "InvoiceItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_recordedById_fkey" FOREIGN KEY ("recordedById") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_quotationId_fkey" FOREIGN KEY ("quotationId") REFERENCES "Quotation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_decidedById_fkey" FOREIGN KEY ("decidedById") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_quotationId_fkey" FOREIGN KEY ("quotationId") REFERENCES "Quotation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- =====================================================================================================
-- PART 2 — rules Prisma cannot express (hand-written; reviewed together with the generated tables above)
-- =====================================================================================================
-- Nothing in this file inserts business data. It adds constraints, triggers and row-level security only.

-- ---------------------------------------------------------------------------------------------------
-- 2.1  Case-insensitive uniqueness, and well-formed identifiers
-- ---------------------------------------------------------------------------------------------------
CREATE UNIQUE INDEX "Brand_name_lower_key"    ON "Brand" (lower("name"));
CREATE UNIQUE INDEX "Category_name_lower_key" ON "Category" (lower("name"));
CREATE UNIQUE INDEX "AdminUser_email_lower_key" ON "AdminUser" (lower("email"));

ALTER TABLE "Brand"    ADD CONSTRAINT "Brand_slug_format"    CHECK ("slug" ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
ALTER TABLE "Category" ADD CONSTRAINT "Category_slug_format" CHECK ("slug" ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
ALTER TABLE "Product"  ADD CONSTRAINT "Product_slug_format"  CHECK ("slug" ~ '^[a-z0-9]+(-[a-z0-9]+)*$');
ALTER TABLE "AdminUser" ADD CONSTRAINT "AdminUser_email_lowercase" CHECK ("email" = lower("email"));

-- Phone numbers are stored as E.164 (+91…); a GSTIN, when present, has the official 15-character shape.
ALTER TABLE "Lead"     ADD CONSTRAINT "Lead_phone_e164"     CHECK ("phone" ~ '^\+[1-9][0-9]{7,14}$');
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_phone_e164" CHECK ("phone" ~ '^\+[1-9][0-9]{7,14}$');
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_gstin_shape"
  CHECK ("gstin" IS NULL OR "gstin" ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$');
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_buyer_gstin_shape"
  CHECK ("buyerGstin" IS NULL OR "buyerGstin" ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$');
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_supplier_gstin_shape"
  CHECK ("supplierGstin" IS NULL OR "supplierGstin" ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$');

-- ---------------------------------------------------------------------------------------------------
-- 2.2  Catalogue: no negative money or stock, sensible ranges. NULL still means "not entered".
-- ---------------------------------------------------------------------------------------------------
ALTER TABLE "Product" ADD CONSTRAINT "Product_prices_not_negative"
  CHECK (coalesce("purchasePrice", 0) >= 0 AND coalesce("wholesalePrice", 0) >= 0 AND coalesce("retailPrice", 0) >= 0);
ALTER TABLE "Product" ADD CONSTRAINT "Product_stock_not_negative"  CHECK ("stockQuantity" IS NULL OR "stockQuantity" >= 0);
ALTER TABLE "Product" ADD CONSTRAINT "Product_moq_at_least_one"    CHECK ("minOrderQuantity" IS NULL OR "minOrderQuantity" >= 1);
ALTER TABLE "Product" ADD CONSTRAINT "Product_gst_rate_range"      CHECK ("gstRatePercent" IS NULL OR ("gstRatePercent" >= 0 AND "gstRatePercent" <= 100));

-- ---------------------------------------------------------------------------------------------------
-- 2.3  Sales documents: amounts, quantities, GST rates
-- ---------------------------------------------------------------------------------------------------
ALTER TABLE "Quotation" ADD CONSTRAINT "Quotation_amounts_not_negative"
  CHECK (coalesce("subtotal", 0) >= 0 AND coalesce("taxTotal", 0) >= 0 AND coalesce("total", 0) >= 0);
ALTER TABLE "QuotationItem" ADD CONSTRAINT "QuotationItem_values_valid"
  CHECK ("quantity" > 0 AND coalesce("unitPrice", 0) >= 0 AND coalesce("lineTotal", 0) >= 0
         AND ("gstRatePercent" IS NULL OR ("gstRatePercent" >= 0 AND "gstRatePercent" <= 100)));
-- A price always says who set it, and "who set it" is never recorded for an unpriced line.
ALTER TABLE "QuotationItem" ADD CONSTRAINT "QuotationItem_price_has_setter"
  CHECK (("unitPrice" IS NULL) = ("priceSetBy" IS NULL));

ALTER TABLE "Order" ADD CONSTRAINT "Order_amounts_not_negative" CHECK ("subtotal" >= 0 AND "taxTotal" >= 0 AND "total" >= 0);
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_values_valid"
  CHECK ("quantity" > 0 AND "unitPrice" >= 0 AND "lineTotal" >= 0 AND "gstRatePercent" >= 0 AND "gstRatePercent" <= 100);

ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_amounts_not_negative"
  CHECK ("subtotal" >= 0 AND "cgstTotal" >= 0 AND "sgstTotal" >= 0 AND "igstTotal" >= 0 AND "total" >= 0);
-- An invoice that has left DRAFT / PENDING_APPROVAL carries its full GST serial number.
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_issued_has_number"
  CHECK ("status" IN ('DRAFT', 'PENDING_APPROVAL')
         OR ("number" IS NOT NULL AND "financialYear" IS NOT NULL AND "sequence" IS NOT NULL AND "issueDate" IS NOT NULL));
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_sequence_positive" CHECK ("sequence" IS NULL OR "sequence" >= 1);
ALTER TABLE "InvoiceItem" ADD CONSTRAINT "InvoiceItem_values_valid"
  CHECK ("quantity" > 0 AND "unitPrice" >= 0 AND "lineTotal" >= 0 AND "gstRatePercent" >= 0 AND "gstRatePercent" <= 100);

ALTER TABLE "Payment" ADD CONSTRAINT "Payment_amount_positive" CHECK ("amount" > 0);
ALTER TABLE "NumberSequence" ADD CONSTRAINT "NumberSequence_not_negative" CHECK ("lastValue" >= 0);

-- ---------------------------------------------------------------------------------------------------
-- 2.4  ApprovalRequest: the owner-approval gate (see lib/ai-sales/policy.ts)
-- ---------------------------------------------------------------------------------------------------
-- Exactly one target record.
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_exactly_one_target"
  CHECK (num_nonnulls("quotationId", "orderId", "invoiceId", "leadId", "customerId") = 1);
-- PENDING has no decision; APPROVED / REJECTED record who, when and (for APPROVED) as OWNER.
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_pending_is_undecided"
  CHECK ("status" <> 'PENDING' OR ("decidedAt" IS NULL AND "executedAt" IS NULL));
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_decision_recorded"
  CHECK ("status" NOT IN ('APPROVED', 'REJECTED') OR ("decidedAt" IS NOT NULL AND "decidedById" IS NOT NULL AND "decidedByRole" IS NOT NULL));
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_approved_by_owner"
  CHECK ("status" <> 'APPROVED' OR "decidedByRole" = 'OWNER');
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_executed_only_if_approved"
  CHECK ("executedAt" IS NULL OR "status" = 'APPROVED');
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_payload_hash_shape" CHECK ("payloadHash" ~ '^[0-9a-f]{64}$');
-- One open request per action and target. COALESCE matters: NULLs are distinct in a plain unique index.
CREATE UNIQUE INDEX "ApprovalRequest_one_pending_per_target"
  ON "ApprovalRequest" ("action", COALESCE("quotationId", "orderId", "invoiceId", "leadId", "customerId"))
  WHERE "status" = 'PENDING';

-- ---------------------------------------------------------------------------------------------------
-- 2.5  Trigger functions (all pin search_path; none is callable by the API roles)
-- ---------------------------------------------------------------------------------------------------

-- updatedAt is maintained by the database as well as by Prisma, so edits made by hand in the Supabase SQL editor
-- do not leave a stale timestamp.
CREATE FUNCTION "tg_touch_updated_at"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  NEW."updatedAt" := now();
  RETURN NEW;
END $$;

-- Evidence is never deleted: use a status (VOID, CANCELLED, EXPIRED…) instead.
CREATE FUNCTION "tg_forbid_delete"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  RAISE EXCEPTION '% rows cannot be deleted; change their status instead', TG_TABLE_NAME USING ERRCODE = 'restrict_violation';
END $$;

-- An approval is frozen the moment it is decided: what the owner approved can never be edited afterwards.
CREATE FUNCTION "tg_approval_request_guard"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  IF OLD."decidedAt" IS NOT NULL THEN
    IF NEW."action" IS DISTINCT FROM OLD."action"
       OR NEW."requestedBy" IS DISTINCT FROM OLD."requestedBy"
       OR NEW."summary" IS DISTINCT FROM OLD."summary"
       OR NEW."payload" IS DISTINCT FROM OLD."payload"
       OR NEW."payloadHash" IS DISTINCT FROM OLD."payloadHash"
       OR NEW."expiresAt" IS DISTINCT FROM OLD."expiresAt"
       OR NEW."decidedAt" IS DISTINCT FROM OLD."decidedAt"
       OR NEW."decidedById" IS DISTINCT FROM OLD."decidedById"
       OR NEW."decidedByRole" IS DISTINCT FROM OLD."decidedByRole"
       OR NEW."quotationId" IS DISTINCT FROM OLD."quotationId"
       OR NEW."orderId" IS DISTINCT FROM OLD."orderId"
       OR NEW."invoiceId" IS DISTINCT FROM OLD."invoiceId"
       OR NEW."leadId" IS DISTINCT FROM OLD."leadId"
       OR NEW."customerId" IS DISTINCT FROM OLD."customerId" THEN
      RAISE EXCEPTION 'ApprovalRequest % is decided and can no longer be changed', OLD."id" USING ERRCODE = 'check_violation';
    END IF;
    -- executedAt may be set once; the only status change allowed after a decision is APPROVED -> EXPIRED (never once executed).
    IF OLD."executedAt" IS NOT NULL AND (NEW."executedAt" IS DISTINCT FROM OLD."executedAt" OR NEW."status" IS DISTINCT FROM OLD."status") THEN
      RAISE EXCEPTION 'ApprovalRequest % was already executed', OLD."id" USING ERRCODE = 'check_violation';
    END IF;
    IF NEW."status" IS DISTINCT FROM OLD."status" AND NOT (OLD."status" = 'APPROVED' AND NEW."status" = 'EXPIRED') THEN
      RAISE EXCEPTION 'ApprovalRequest % cannot change status from % to %', OLD."id", OLD."status", NEW."status" USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

-- A quotation beyond DRAFT must be complete: at least one line, every line priced, totals present.
-- A SENT / ACCEPTED quotation's lines are frozen (see "tg_quotation_item_guard").
CREATE FUNCTION "tg_quotation_guard"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  IF NEW."status" NOT IN ('DRAFT', 'CANCELLED', 'REJECTED', 'EXPIRED') THEN
    IF NEW."subtotal" IS NULL OR NEW."taxTotal" IS NULL OR NEW."total" IS NULL THEN
      RAISE EXCEPTION 'Quotation % cannot leave DRAFT without its totals', NEW."id" USING ERRCODE = 'check_violation';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "QuotationItem" WHERE "quotationId" = NEW."id") THEN
      RAISE EXCEPTION 'Quotation % cannot leave DRAFT without any lines', NEW."id" USING ERRCODE = 'check_violation';
    END IF;
    IF EXISTS (SELECT 1 FROM "QuotationItem" WHERE "quotationId" = NEW."id" AND ("unitPrice" IS NULL OR "lineTotal" IS NULL OR "gstRatePercent" IS NULL)) THEN
      RAISE EXCEPTION 'Quotation % has unpriced lines and cannot leave DRAFT', NEW."id" USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

-- Quotation lines: (a) a price set by the AI agent needs an APPROVED PROPOSE_PRICE approval for this quotation;
-- (b) lines of a quotation that has been sent or accepted cannot change.
CREATE FUNCTION "tg_quotation_item_guard"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
DECLARE parent_status "QuotationStatus";
BEGIN
  SELECT "status" INTO parent_status FROM "Quotation" WHERE "id" = NEW."quotationId";
  IF parent_status IN ('SENT', 'ACCEPTED') THEN
    RAISE EXCEPTION 'Lines of a % quotation cannot be changed', parent_status USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."priceSetBy" = 'AI_AGENT' THEN
    IF NEW."priceApprovalId" IS NULL OR NOT EXISTS (
      SELECT 1 FROM "ApprovalRequest" a
       WHERE a."id" = NEW."priceApprovalId" AND a."action" = 'PROPOSE_PRICE' AND a."status" = 'APPROVED'
         AND a."decidedByRole" = 'OWNER' AND a."quotationId" = NEW."quotationId") THEN
      RAISE EXCEPTION 'A price set by the AI agent needs an approved PROPOSE_PRICE request for this quotation' USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

-- Customer on an order must be the customer on its quotation; on an invoice, the customer on its order.
CREATE FUNCTION "tg_order_customer_matches_quotation"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  IF NEW."quotationId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "Quotation" q WHERE q."id" = NEW."quotationId" AND q."customerId" = NEW."customerId") THEN
    RAISE EXCEPTION 'Order customer differs from its quotation''s customer' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION "tg_invoice_guard"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "Order" o WHERE o."id" = NEW."orderId" AND o."customerId" = NEW."customerId") THEN
    RAISE EXCEPTION 'Invoice customer differs from its order''s customer' USING ERRCODE = 'check_violation';
  END IF;
  -- Once issued, an invoice is immutable apart from its status (e.g. PAID, VOID) and the e-invoice reference.
  IF TG_OP = 'UPDATE' AND OLD."status" NOT IN ('DRAFT', 'PENDING_APPROVAL') THEN
    IF NEW."number" IS DISTINCT FROM OLD."number" OR NEW."financialYear" IS DISTINCT FROM OLD."financialYear"
       OR NEW."sequence" IS DISTINCT FROM OLD."sequence" OR NEW."issueDate" IS DISTINCT FROM OLD."issueDate"
       OR NEW."dueDate" IS DISTINCT FROM OLD."dueDate" OR NEW."currency" IS DISTINCT FROM OLD."currency"
       OR NEW."subtotal" IS DISTINCT FROM OLD."subtotal" OR NEW."cgstTotal" IS DISTINCT FROM OLD."cgstTotal"
       OR NEW."sgstTotal" IS DISTINCT FROM OLD."sgstTotal" OR NEW."igstTotal" IS DISTINCT FROM OLD."igstTotal"
       OR NEW."total" IS DISTINCT FROM OLD."total"
       OR NEW."buyerName" IS DISTINCT FROM OLD."buyerName" OR NEW."buyerAddress" IS DISTINCT FROM OLD."buyerAddress"
       OR NEW."buyerGstin" IS DISTINCT FROM OLD."buyerGstin" OR NEW."placeOfSupply" IS DISTINCT FROM OLD."placeOfSupply"
       OR NEW."supplierName" IS DISTINCT FROM OLD."supplierName" OR NEW."supplierAddress" IS DISTINCT FROM OLD."supplierAddress"
       OR NEW."supplierGstin" IS DISTINCT FROM OLD."supplierGstin"
       OR NEW."orderId" IS DISTINCT FROM OLD."orderId" OR NEW."customerId" IS DISTINCT FROM OLD."customerId"
       OR NEW."createdBy" IS DISTINCT FROM OLD."createdBy" THEN
      RAISE EXCEPTION 'Invoice % has been issued and can only change status or e-invoice reference', OLD."id" USING ERRCODE = 'check_violation';
    END IF;
    IF OLD."irn" IS NOT NULL AND NEW."irn" IS DISTINCT FROM OLD."irn" THEN
      RAISE EXCEPTION 'Invoice % already has an e-invoice reference', OLD."id" USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION "tg_invoice_item_guard"() RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
DECLARE parent_status "InvoiceStatus";
BEGIN
  SELECT "status" INTO parent_status FROM "Invoice" WHERE "id" = NEW."invoiceId";
  IF parent_status NOT IN ('DRAFT', 'PENDING_APPROVAL') THEN
    RAISE EXCEPTION 'Lines of an issued invoice cannot be changed' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

-- ---------------------------------------------------------------------------------------------------
-- 2.6  Attach the triggers
-- ---------------------------------------------------------------------------------------------------
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT c.table_name FROM information_schema.columns c
            WHERE c.table_schema = 'public' AND c.column_name = 'updatedAt' ORDER BY 1 LOOP
    EXECUTE format('CREATE TRIGGER "tg_%s_touch_updated_at" BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION "tg_touch_updated_at"()', t, t);
  END LOOP;
END $$;

-- Records that must outlive any clean-up. (Lead / Customer / Enquiry stay deletable at the database level so that a
-- personal-data erasure request can be honoured; their FKs still stop deletion while documents refer to them.)
CREATE TRIGGER "tg_ApprovalRequest_no_delete" BEFORE DELETE ON "ApprovalRequest" FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();
CREATE TRIGGER "tg_Payment_no_delete"         BEFORE DELETE ON "Payment"         FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();
CREATE TRIGGER "tg_FollowUp_no_delete"        BEFORE DELETE ON "FollowUp"        FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();
CREATE TRIGGER "tg_Quotation_no_delete"       BEFORE DELETE ON "Quotation"       FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();
CREATE TRIGGER "tg_Order_no_delete"           BEFORE DELETE ON "Order"           FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();
CREATE TRIGGER "tg_Invoice_no_delete"         BEFORE DELETE ON "Invoice"         FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();
CREATE TRIGGER "tg_InvoiceItem_no_delete"     BEFORE DELETE ON "InvoiceItem"     FOR EACH ROW EXECUTE FUNCTION "tg_forbid_delete"();

CREATE TRIGGER "tg_ApprovalRequest_guard"  BEFORE UPDATE ON "ApprovalRequest" FOR EACH ROW EXECUTE FUNCTION "tg_approval_request_guard"();
CREATE TRIGGER "tg_Quotation_guard"        BEFORE INSERT OR UPDATE ON "Quotation"     FOR EACH ROW EXECUTE FUNCTION "tg_quotation_guard"();
CREATE TRIGGER "tg_QuotationItem_guard"    BEFORE INSERT OR UPDATE ON "QuotationItem" FOR EACH ROW EXECUTE FUNCTION "tg_quotation_item_guard"();
CREATE TRIGGER "tg_Order_customer_check"   BEFORE INSERT OR UPDATE ON "Order"         FOR EACH ROW EXECUTE FUNCTION "tg_order_customer_matches_quotation"();
CREATE TRIGGER "tg_Invoice_guard"          BEFORE INSERT OR UPDATE ON "Invoice"       FOR EACH ROW EXECUTE FUNCTION "tg_invoice_guard"();
CREATE TRIGGER "tg_InvoiceItem_guard"      BEFORE INSERT OR UPDATE ON "InvoiceItem"   FOR EACH ROW EXECUTE FUNCTION "tg_invoice_item_guard"();

-- Trigger functions are not meant to be called by anyone.
REVOKE ALL ON FUNCTION "tg_touch_updated_at"(), "tg_forbid_delete"(), "tg_approval_request_guard"(), "tg_quotation_guard"(),
  "tg_quotation_item_guard"(), "tg_order_customer_matches_quotation"(), "tg_invoice_guard"(), "tg_invoice_item_guard"() FROM PUBLIC;

-- ---------------------------------------------------------------------------------------------------
-- 2.7  Row Level Security
-- ---------------------------------------------------------------------------------------------------
-- Model: this application reaches the database ONLY from the server (Prisma over DATABASE_URL, as the table-owner
-- role). The owner role bypasses RLS, so the app is unaffected. Supabase additionally exposes every table in the
-- `public` schema to the browser-facing API roles `anon` and `authenticated`; for those roles NOTHING is readable or
-- writable: RLS is enabled on every table, access is revoked, and an explicit RESTRICTIVE policy denies all rows, so
-- that a permissive policy added later by mistake still cannot open a table. In particular the purchase / wholesale /
-- retail prices on "Product" can never be read through the Supabase API.
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tableowner = current_user LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;

  -- The roles below exist on Supabase; skip quietly on a plain PostgreSQL (CI, local development).
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tableowner = current_user LOOP
      EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', t);
      EXECUTE format('CREATE POLICY "deny_api_access" ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)', t);
    END LOOP;
    -- Tables and functions created later by this role must not be handed to the API roles automatically.
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon, authenticated;
  END IF;
END $$;
