import type { Metadata } from "next";
import { siteConfig } from "@/lib/config/site";

/** Default social-share image, generated by app/opengraph-image.tsx. */
export const defaultOgImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — ${siteConfig.tagline}`,
};

/** Absolute URL for a site path. */
export function absoluteUrl(path = "/"): string {
  return `${siteConfig.url}${path.startsWith("/") ? path : `/${path}`}`;
}

interface PageMetadataInput {
  /** Page title. The site name is appended by the root layout's title template. */
  title: string;
  description: string;
  /** Canonical path, e.g. "/bulk-orders". */
  path: string;
  /** Set for pages that should not appear in search results (search results, thank-you pages…). */
  noIndex?: boolean;
  /** Use the title exactly as given, without the " | Munna Pen Center" suffix. */
  absoluteTitle?: boolean;
}

/** Consistent title / description / canonical / Open Graph / Twitter metadata for a page. */
export function pageMetadata({ title, description, path, noIndex, absoluteTitle }: PageMetadataInput): Metadata {
  const fullTitle = absoluteTitle ? title : `${title} | ${siteConfig.name}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: siteConfig.locale,
      siteName: siteConfig.name,
      title: fullTitle,
      description,
      url: path,
      // A page-level `openGraph` replaces the root one wholesale, so the image must be repeated here.
      images: [defaultOgImage],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [defaultOgImage.url] },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}

/** Organisation details for structured data. Only facts supplied by the owner. */
export function organizationJsonLd() {
  const { name, description, contact, location } = siteConfig;
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": absoluteUrl("/#organization"),
    name,
    url: siteConfig.url,
    logo: absoluteUrl("/brand/logo-mark.svg"),
    description,
    telephone: contact.phoneE164,
    address: {
      "@type": "PostalAddress",
      addressLocality: location.locality,
      addressRegion: location.region,
      addressCountry: location.countryCode,
      ...(location.streetAddress ? { streetAddress: location.streetAddress } : {}),
      ...(location.postalCode ? { postalCode: location.postalCode } : {}),
    },
    areaServed: { "@type": "Country", name: location.country },
    contactPoint: [contact.phoneE164, ...contact.additionalPhones.map((phone) => phone.e164)].map((telephone) => ({
      "@type": "ContactPoint",
      contactType: "sales",
      telephone,
      areaServed: location.countryCode,
    })),
    ...(contact.email ? { email: contact.email } : {}),
  };
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": absoluteUrl("/#website"),
    name: siteConfig.name,
    url: siteConfig.url,
    publisher: { "@id": absoluteUrl("/#organization") },
    potentialAction: {
      "@type": "SearchAction",
      target: { "@type": "EntryPoint", urlTemplate: `${siteConfig.url}/products?q={search_term_string}` },
      "query-input": "required name=search_term_string",
    },
  };
}

export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}
