import { brands } from "@/data/brands";
import { categories } from "@/data/categories";
import { products } from "@/data/products";

/**
 * Renders the owner-supplied catalogue (data/categories.ts, data/brands.ts, data/products.ts) as plain SQL that can be
 * pasted into the Supabase SQL Editor — so loading it needs no database password on anyone's computer.
 *
 * Create-only and repeatable: every row is inserted only if its slug is missing (ON CONFLICT DO NOTHING), so running it
 * twice, or after the owner has edited things, changes nothing. It contains NO SKUs, prices, GST rates, HSN codes, stock,
 * pack sizes, brands on products or customers. `npm run db:seed-sql` rewrites prisma/seed/catalogue.sql; a test fails if
 * the committed file is out of date.
 */
/**
 * A SQL string literal for `value`. Single quotes are doubled, so no value can end the string early. Anything that is
 * not plain printable ASCII (an em dash, an accented letter, a line break...) is written as chr(<code point>), so the
 * generated file stays pure ASCII and survives being copied through any browser, editor or chat window unchanged.
 */
export const q = (value: string) => {
  const parts: string[] = [];
  let run = "";
  const flush = () => {
    if (run) parts.push(`'${run.replace(/'/g, "''")}'`);
    run = "";
  };
  for (const character of value) {
    const code = character.codePointAt(0) ?? 0;
    if (code >= 0x20 && code <= 0x7e) run += character;
    else {
      flush();
      parts.push(`chr(${code})`);
    }
  }
  flush();
  return parts.length ? parts.join(" || ") : "''";
};
const arr = (values: string[]) => (values.length ? `ARRAY[${values.map(q).join(", ")}]::text[]` : "ARRAY[]::text[]");

export function renderSeedSql(): string {
  const lines: string[] = [
    "-- Munna Pen Center - owner-supplied catalogue (generated by `npm run db:seed-sql` from data/; do not edit by hand).",
    `-- ${categories.length} categories, ${brands.length} brands, ${products.length} products. No SKUs, prices, GST rates, HSN codes, stock or customers.`,
    "-- Safe to run more than once: a row is created only if its slug is missing; nothing is ever overwritten.",
    "BEGIN;",
    "",
    "INSERT INTO \"Category\" (\"id\", \"slug\", \"name\", \"summary\", \"description\", \"seoTitle\", \"seoDescription\", \"sortOrder\", \"updatedAt\") VALUES",
    categories
      .map((c) => `  (gen_random_uuid()::text, ${q(c.slug)}, ${q(c.name)}, ${q(c.summary)}, ${q(c.description)}, ${q(c.seoTitle)}, ${q(c.seoDescription)}, ${c.sortOrder}, now())`)
      .join(",\n"),
    "ON CONFLICT (\"slug\") DO NOTHING;",
    "",
    "INSERT INTO \"Brand\" (\"id\", \"slug\", \"name\", \"isListedPublicly\", \"sortOrder\", \"updatedAt\") VALUES",
    brands.map((b, index) => `  (gen_random_uuid()::text, ${q(b.slug)}, ${q(b.name)}, ${b.listedPublicly ? "true" : "false"}, ${(index + 1) * 10}, now())`).join(",\n"),
    "ON CONFLICT (\"slug\") DO NOTHING;",
    "",
    "INSERT INTO \"Product\" (\"id\", \"slug\", \"name\", \"shortDescription\", \"categoryId\", \"tags\", \"isFeatured\", \"status\", \"updatedAt\") VALUES",
    products
      .map(
        (p) =>
          `  (gen_random_uuid()::text, ${q(p.slug)}, ${q(p.name)}, ${q(p.shortDescription)}, (SELECT "id" FROM "Category" WHERE "slug" = ${q(p.categoryId)}), ${arr(p.tags)}, ${p.isFeatured ? "true" : "false"}, 'ACTIVE', now())`,
      )
      .join(",\n"),
    "ON CONFLICT (\"slug\") DO NOTHING;",
    "",
    "COMMIT;",
    "",
    "-- What is in the database now:",
    "SELECT (SELECT count(*) FROM \"Category\") AS categories, (SELECT count(*) FROM \"Brand\") AS brands, (SELECT count(*) FROM \"Product\") AS products;",
    "",
  ];
  return lines.join("\n");
}
